name: Cyclonus Network Policy Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'npm/**'
      - 'github/**'
      - 'test/**'
  schedule:
    # run once a day at midnight
    - cron: '0 0 * * *'

jobs:
  cyclonus-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - name: Setup Kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
          config: ./test/kind/kind.yaml
          name: npm-kind

      - name: Check Kind
        run: |
          kubectl get po -owide -A

      - name: Make NPM image
        run: |
          VERSION=cyclonus IMAGE_PLATFORM_ARCHES=linux/amd64 IMAGE_ACTION=load make azure-npm-image
      
      - name: Install Azure NPM
        run: |
          sed -i 's/mcr.microsoft.com\/containernetworking\/azure-npm:.*/acnpublic.azurecr.io\/azure-npm:cyclonus/' ./npm/azure-npm.yaml
          kind load docker-image acnpublic.azurecr.io/azure-npm:cyclonus --name npm-kind
          kubectl apply -f ./npm/azure-npm.yaml
    
      - name: Check Cluster Components
        run: |
          sleep 10
          kubectl get po -owide -A
          kubectl describe ds azure-npm -n kube-system

      - name: Run Cyclonus network policy test
        run: make test-cyclonus

      - name: Fetch logs
        if: always()
        run: |
          kubectl logs -n kube-system -l k8s-app=azure-npm --tail -1 --prefix > npm-logs.txt
          mv ./test/cyclonus/cyclonus-test.txt ./cyclonus-test.txt

      - name: 'Upload Logs'
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: logs
          path: |
            ./npm-logs.txt
            ./cyclonus-test.txt
